# Generated by Django 3.2.13 on 2022-06-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=250)),
                ('Img1', models.ImageField(upload_to='pics')),
                ('Desc1', models.TextField()),
            ],
        ),
    ]
